# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import safeEntry_pb2 as safeEntry__pb2


class safeEntryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckIn = channel.unary_unary(
                '/safeEntry.safeEntry/CheckIn',
                request_serializer=safeEntry__pb2.CheckInRequest.SerializeToString,
                response_deserializer=safeEntry__pb2.Result.FromString,
                )
        self.CheckOut = channel.unary_unary(
                '/safeEntry.safeEntry/CheckOut',
                request_serializer=safeEntry__pb2.CheckOutRequest.SerializeToString,
                response_deserializer=safeEntry__pb2.Result.FromString,
                )


class safeEntryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_safeEntryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckIn': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIn,
                    request_deserializer=safeEntry__pb2.CheckInRequest.FromString,
                    response_serializer=safeEntry__pb2.Result.SerializeToString,
            ),
            'CheckOut': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOut,
                    request_deserializer=safeEntry__pb2.CheckOutRequest.FromString,
                    response_serializer=safeEntry__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'safeEntry.safeEntry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class safeEntry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/safeEntry.safeEntry/CheckIn',
            safeEntry__pb2.CheckInRequest.SerializeToString,
            safeEntry__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/safeEntry.safeEntry/CheckOut',
            safeEntry__pb2.CheckOutRequest.SerializeToString,
            safeEntry__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
