# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: safeEntry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsafeEntry.proto\x12\tsafeEntry\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n\x0e\x43heckInRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"[\n\x0f\x43heckOutRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x19\n\x06Result\x12\x0f\n\x07message\x18\x01 \x01(\t2\x7f\n\tsafeEntry\x12\x37\n\x07\x43heckIn\x12\x19.safeEntry.CheckInRequest\x1a\x11.safeEntry.Result\x12\x39\n\x08\x43heckOut\x12\x1a.safeEntry.CheckOutRequest\x1a\x11.safeEntry.Resultb\x06proto3')



_CHECKINREQUEST = DESCRIPTOR.message_types_by_name['CheckInRequest']
_CHECKOUTREQUEST = DESCRIPTOR.message_types_by_name['CheckOutRequest']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
CheckInRequest = _reflection.GeneratedProtocolMessageType('CheckInRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKINREQUEST,
  '__module__' : 'safeEntry_pb2'
  # @@protoc_insertion_point(class_scope:safeEntry.CheckInRequest)
  })
_sym_db.RegisterMessage(CheckInRequest)

CheckOutRequest = _reflection.GeneratedProtocolMessageType('CheckOutRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTREQUEST,
  '__module__' : 'safeEntry_pb2'
  # @@protoc_insertion_point(class_scope:safeEntry.CheckOutRequest)
  })
_sym_db.RegisterMessage(CheckOutRequest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'safeEntry_pb2'
  # @@protoc_insertion_point(class_scope:safeEntry.Result)
  })
_sym_db.RegisterMessage(Result)

_SAFEENTRY = DESCRIPTOR.services_by_name['safeEntry']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKINREQUEST._serialized_start=63
  _CHECKINREQUEST._serialized_end=153
  _CHECKOUTREQUEST._serialized_start=155
  _CHECKOUTREQUEST._serialized_end=246
  _RESULT._serialized_start=248
  _RESULT._serialized_end=273
  _SAFEENTRY._serialized_start=275
  _SAFEENTRY._serialized_end=402
# @@protoc_insertion_point(module_scope)
